"use client"
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { ethers } from "ethers";
import { AlertCircle, CheckCircle2, FileCode, Loader2, Play, Terminal } from "lucide-react";
import { useState } from 'react';
import { toast } from "sonner";
import { data } from "./data";

export default function ComputeSandbox({ purchasedData, account }) {
    const [selectedHashes, setSelectedHashes] = useState([]);
    const [script, setScript] = useState(data);
    const [loading, setLoading] = useState(false);
    const [jobResult, setJobResult] = useState(null);

    const toggleHash = (hash) => {
        setSelectedHashes(prev => 
            prev.includes(hash) ? prev.filter(h => h !== hash) : [...prev, hash]
        );
    }

    const runJob = async () => {
        if (selectedHashes.length === 0) {
            toast.error("Please select at least one dataset");
            return;
        }

        setLoading(true);
        setJobResult(null);

        try {
            if (!window.ethereum) throw new Error("No crypto wallet found");
            const provider = new ethers.BrowserProvider(window.ethereum);
            const signer = await provider.getSigner();
            
            // In a real scenario, the message would contain the jobId generated by the server
            // But for simplicity in this flow, we'll sign a generic message or pre-fetch a JOB_ID
            // Here we'll just sign a fixed string to prove identity
            const signature = await signer.signMessage("START_COMPUTE_JOB");

            const response = await fetch("http://localhost:5000/compute/execute", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    userAddress: account,
                    signature: signature,
                    ipfsHashes: selectedHashes,
                    script: script
                })
            });

            const data = await response.json();
            if (!response.ok) throw new Error(data.error || "Execution failed");

            setJobResult(data);
            toast.success("Job Completed Successfully");
        } catch (error) {
            console.error(error);
            toast.error("Execution Error: " + error.message);
        } finally {
            setLoading(false);
        }
    }

    return (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 p-1">
            <div className="space-y-6">
                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <FileCode className="h-5 w-5 text-purple-600" />
                            1. Select Datasets
                        </CardTitle>
                        <CardDescription>Only purchased datasets are visible</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="max-h-[300px] overflow-y-auto space-y-2 border rounded-md p-2 bg-gray-50/50">
                            {purchasedData.length === 0 ? (
                                <p className="text-sm text-gray-500 italic">No data purchased yet.</p>
                            ) : purchasedData.map((data, idx) => (
                                <div key={idx} className="flex items-center space-x-3 p-2 bg-white rounded border border-gray-100 hover:border-purple-200 transition-colors">
                                    <Checkbox 
                                        id={`check-${idx}`} 
                                        checked={selectedHashes.includes(data.ipfsHash)}
                                        onCheckedChange={() => toggleHash(data.ipfsHash)}
                                    />
                                    <label htmlFor={`check-${idx}`} className="text-xs font-mono truncate cursor-pointer flex-1">
                                        {data.ipfsHash}
                                        <span className="block text-[10px] text-gray-400 font-sans">Purchased: {new Date(Number(data.timestamp)*1000).toLocaleDateString()}</span>
                                    </label>
                                </div>
                            ))}
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Terminal className="h-5 w-5 text-green-600" />
                            2. Training Script (Python)
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <Textarea 
                            className="font-mono text-sm h-[400px] bg-gray-900 text-green-400 border-none focus-visible:ring-1 focus-visible:ring-purple-500" 
                            value={script}
                            onChange={(e) => setScript(e.target.value)}
                        />
                        <Button 
                            className="w-full mt-4 bg-[#703FA1] hover:bg-[#5d348a] text-white" 
                            onClick={runJob}
                            disabled={loading || purchasedData.length === 0}
                        >
                            {loading ? (
                                <>
                                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                    Provisioning Sandbox...
                                </>
                            ) : (
                                <>
                                    <Play className="mr-2 h-4 w-4" />
                                    Execute Job
                                </>
                            )}
                        </Button>
                    </CardContent>
                </Card>
            </div>

            <div className="space-y-6">
                <Card className="h-full flex flex-col">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Terminal className="h-5 w-5 text-blue-600" />
                            Execution Logs & Results
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="flex-1 overflow-hidden flex flex-col gap-4">
                        <div className="flex-1 bg-black rounded-lg p-4 font-mono text-xs text-blue-100 overflow-y-auto whitespace-pre-wrap border border-gray-800">
                            {jobResult ? (
                                <>
                                    <div className="text-green-400 mb-2">{" >>> "} JOB ID: {jobResult.jobId}</div>
                                    {jobResult.logs}
                                    <div className={`mt-2 ${jobResult.exitCode === 0 ? 'text-green-400' : 'text-red-400'}`}>
                                        Process exited with code {jobResult.exitCode}
                                    </div>
                                </>
                            ) : loading ? (
                                <div className="flex items-center gap-2 text-gray-500 italic animate-pulse">
                                    Initializing environment...
                                </div>
                            ) : (
                                <div className="text-gray-600 italic">Logs will appear here after execution...</div>
                            )}
                        </div>

                        {jobResult?.results && Object.keys(jobResult.results).length > 0 && (
                            <div className="space-y-2">
                                <h4 className="text-sm font-bold flex items-center gap-2">
                                    <CheckCircle2 className="h-4 w-4 text-green-550" /> Artifacts Produced
                                </h4>
                                <div className="grid grid-cols-1 gap-2">
                                    {Object.entries(jobResult.results).map(([filename, content]) => (
                                        <div key={filename} className="p-3 bg-green-50/50 border border-green-100 rounded-md">
                                            <p className="text-xs font-bold text-green-800 mb-1">{filename}</p>
                                            <pre className="text-[10px] text-green-700 overflow-x-auto">
                                                {content}
                                            </pre>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {jobResult?.status === "failed" && (
                            <div className="p-3 bg-red-50 border border-red-100 rounded-md flex items-center gap-3">
                                <AlertCircle className="h-5 w-5 text-red-600" />
                                <div className="text-xs text-red-800 font-medium">
                                    Job failed. Check logs for details.
                                </div>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
