"use client"

import SafeDocumentViewer from "@/components/safe-document-viewer"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Activity, AlertCircle, Clock, FileText, Heart, Loader2, Phone, ShieldAlert, User } from "lucide-react"
import { useSearchParams } from "next/navigation"
import { Suspense, useEffect, useState } from "react"

function EmergencyViewContent() {
  const searchParams = useSearchParams()
  const patientId = searchParams.get("p") || searchParams.get("patientId")
  const secret = searchParams.get("s") || searchParams.get("secret")

  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [data, setData] = useState(null)
  const [token, setToken] = useState(null)
  const [selectedDoc, setSelectedDoc] = useState(null)
  const [timeLeft, setTimeLeft] = useState(3600) // 1 hour in seconds

  const API_URL = "http://localhost:5000/emergency"

  useEffect(() => {
    // We don't want to immediately show an error if params are null on very first mount
    // as Next.js can sometimes have a delay. But with Suspense it should be there.
    // However, let's reset error on every dependency change.
    setError(null)
    
    // If we've been loading for a bit and still no params, then show error.
    // But since this is a dedicated page, we expect params from the start.
    if (!patientId || !secret) {
      const timer = setTimeout(() => {
        if (!patientId || !secret) {
          setError(`Invalid Emergency Link: Missing parameters. Please ensure you used the full link generated by the patient. Detected: p=${patientId}, s=${secret ? 'PROVIDED' : 'MISSING'}`)
          setLoading(false)
        }
      }, 500) // Small grace period
      return () => clearTimeout(timer)
    }

    const fetchAccess = async () => {
      try {
        setLoading(true)
        // 1. Trigger access to get 1-hour token
        const authRes = await fetch(`${API_URL}/access`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ patientId, secret })
        })

        const authData = await authRes.json()
        if (!authRes.ok) throw new Error(authData.error || "Failed to trigger emergency access")

        const tokenVal = authData.token
        setToken(tokenVal)

        // 2. Fetch medical data using the token
        const dataRes = await fetch(`${API_URL}/data`, {
          headers: { "Authorization": `Bearer ${tokenVal}` }
        })

        const medicalData = await dataRes.json()
        if (!dataRes.ok) throw new Error(medicalData.error || "Failed to fetch medical data")

        setData(medicalData)
      } catch (err) {
        console.error("Emergency Access Error:", err)
        setError(err.message)
      } finally {
        setLoading(false)
      }
    }

    fetchAccess()
  }, [patientId, secret])

  // Countdown timer
  useEffect(() => {
    if (!data) return
    const timer = setInterval(() => {
      setTimeLeft(prev => {
          if (prev <= 1) {
              clearInterval(timer)
              setError("Emergency session expired.")
              setData(null)
              return 0
          }
          return prev - 1
      })
    }, 1000)
    return () => clearInterval(timer)
  }, [data])

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
        <Loader2 className="w-12 h-12 text-red-600 animate-spin mb-4" />
        <p className="text-xl font-medium text-slate-700">Verifying Emergency Access...</p>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-white flex flex-col items-center justify-center p-4">
        <div className="bg-red-50 p-8 rounded-2xl border border-red-100 max-w-md w-full text-center">
            <AlertCircle className="w-16 h-16 text-red-600 mx-auto mb-4" />
            <h1 className="text-2xl font-bold text-slate-900 mb-2">Access Error</h1>
            <p className="text-slate-600 mb-6">{error}</p>
            <Button variant="outline" className="w-full" onClick={() => window.location.reload()}>Retry</Button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-8">
      <div className="max-w-3xl mx-auto space-y-6">
        
        {selectedDoc && (
            <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
                <div className="w-full max-w-5xl">
                    <SafeDocumentViewer 
                        ipfsHash={selectedDoc.ipfsHash} 
                        patientAddress={data?.walletAddress} 
                        emergencyToken={token}
                        onClose={() => setSelectedDoc(null)} 
                    />
                </div>
            </div>
        )}
        
        {/* Header Hook */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center bg-red-600 text-white p-6 rounded-2xl shadow-xl gap-4">
            <div className="flex items-center gap-4">
                <div className="bg-white/20 p-3 rounded-xl backdrop-blur-sm">
                    <ShieldAlert className="w-8 h-8" />
                </div>
                <div>
                    <h1 className="text-2xl font-bold capitalize">EMERGENCY MEDICAL VIEW</h1>
                    <p className="text-red-100 flex items-center gap-2">
                        <User className="w-4 h-4" /> Patient: {data?.name}
                    </p>
                </div>
            </div>
            <div className="bg-black/20 px-4 py-2 rounded-lg flex items-center gap-2 font-mono">
                <Clock className="w-4 h-4" /> SECURE SESSION EXPIRES: {formatTime(timeLeft)}
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Primary Vitals Card */}
            <Card className="border-none shadow-md overflow-hidden">
                <CardHeader className="bg-white border-b">
                    <CardTitle className="flex items-center gap-2 text-slate-800">
                        <Heart className="w-5 h-5 text-red-500" /> Essential Vitals
                    </CardTitle>
                </CardHeader>
                <CardContent className="p-6 space-y-6">
                    <div className="grid grid-cols-2 gap-4">
                        <div className="bg-slate-50 p-4 rounded-xl">
                            <p className="text-xs text-slate-500 uppercase font-semibold">Blood Group</p>
                            <p className="text-2xl font-bold text-red-600">{data?.bloodGroup || "Unknown"}</p>
                        </div>
                        <div className="bg-slate-50 p-4 rounded-xl">
                            <p className="text-xs text-slate-500 uppercase font-semibold">Age</p>
                            <p className="text-2xl font-bold text-slate-700">{data?.age} Yrs</p>
                        </div>
                    </div>

                    {data?.vitals && (
                        <div className="space-y-4 pt-2">
                            <p className="text-xs text-slate-500 uppercase font-semibold">Recent Health Snapshot</p>
                            <div className="grid grid-cols-1 gap-2">
                                <div className="flex justify-between p-2 bg-slate-50 rounded-lg">
                                    <span className="text-slate-600 text-sm">Blood Pressure</span>
                                    <span className="font-bold text-slate-800">{data.vitals.bloodPressure}</span>
                                </div>
                                <div className="flex justify-between p-2 bg-slate-50 rounded-lg">
                                    <span className="text-slate-600 text-sm">Heart Rate</span>
                                    <span className="font-bold text-slate-800">{data.vitals.heartRate}</span>
                                </div>
                                <div className="flex justify-between p-2 bg-slate-50 rounded-lg">
                                    <span className="text-slate-600 text-sm">Temperature</span>
                                    <span className="font-bold text-slate-800">{data.vitals.temperature}</span>
                                </div>
                            </div>
                        </div>
                    )}
                    
                    <div className="space-y-3">
                        <p className="text-xs text-slate-500 uppercase font-semibold flex items-center gap-2">
                             Allergies & Medical Alerts
                        </p>
                        <div className="bg-yellow-50 border border-yellow-100 p-4 rounded-xl">
                             <p className="text-sm text-yellow-800">
                                This field is encrypted in the full record. Secondary protocol check recommended.
                             </p>
                        </div>
                    </div>
                </CardContent>
            </Card>

            {/* Emergency Contacts Card */}
            <Card className="border-none shadow-md overflow-hidden">
                <CardHeader className="bg-white border-b">
                    <CardTitle className="flex items-center gap-2 text-slate-800">
                        <Phone className="w-5 h-5 text-blue-500" /> Emergency Contacts
                    </CardTitle>
                </CardHeader>
                <CardContent className="p-0">
                    <div className="divide-y max-h-[380px] overflow-y-auto">
                        {data?.emergencyContacts?.length > 0 ? (
                            data.emergencyContacts.map((contact, i) => (
                                <div key={i} className="p-4 hover:bg-slate-50 transition-colors text-slate-800">
                                    <div className="flex justify-between items-start mb-1">
                                        <p className="font-bold">{contact.name}</p>
                                        <span className="text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full uppercase font-bold">
                                            {contact.relationship}
                                        </span>
                                    </div>
                                    <a href={`tel:${contact.contactNumber}`} className="text-lg text-blue-600 font-semibold flex items-center gap-2 mt-2">
                                        <div className="bg-blue-600 p-1.5 rounded-lg text-white">
                                            <Phone className="w-3 h-3" />
                                        </div>
                                        {contact.contactNumber}
                                    </a>
                                </div>
                            ))
                        ) : (
                            <div className="p-8 text-center text-slate-500">
                                No emergency contacts listed.
                            </div>
                        )}
                    </div>
                </CardContent>
            </Card>
        </div>

        {/* Medical Documents Card */}
        <Card className="border-none shadow-md overflow-hidden">
            <CardHeader className="bg-white border-b">
                <CardTitle className="flex items-center gap-2 text-slate-800">
                    <FileText className="w-5 h-5 text-indigo-500" /> Medical Documents & History
                </CardTitle>
                <p className="text-xs text-slate-500">View-only records for first responders</p>
            </CardHeader>
            <CardContent className="p-0">
                <div className="divide-y border-t border-slate-100">
                    {data?.medicalRecords?.length > 0 ? (
                        data.medicalRecords.map((record, i) => (
                            <div key={i} className="p-4 hover:bg-slate-50 transition-colors flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                    <div className="bg-indigo-50 p-2 rounded-lg text-indigo-600">
                                        <FileText className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="font-bold text-slate-800 leading-none mb-1">{record.fileName}</p>
                                        <p className="text-xs text-slate-500">{record.hospital} • {record.date}</p>
                                    </div>
                                </div>
                                <Button 
                                    size="sm" 
                                    variant="ghost" 
                                    className="text-indigo-600 text-xs font-semibold"
                                    onClick={() => setSelectedDoc(record)}
                                >
                                    View Link
                                </Button>
                            </div>
                        ))
                    ) : (
                        <div className="p-8 text-center text-slate-500">
                            No medical records found in emergency bundle.
                        </div>
                    )}
                </div>
            </CardContent>
        </Card>

        {/* Action Footer */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm text-center space-y-4">
             <div className="flex items-center justify-center gap-2 text-slate-400 text-sm">
                 <Activity className="w-4 h-4" />
                 Encrypted via MediSecure Protocol (P-Zero)
             </div>
             <p className="text-slate-500 text-xs italic">
                 Note to First Responders: This information is shared per patient's pre-authorized emergency consent. Access is logged.
             </p>
             <Button variant="outline" className="text-slate-600 border-slate-200" onClick={() => window.print()}>
                 Print Medical Summary
             </Button>
        </div>

      </div>
    </div>
  )
}

export default function EmergencyViewPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
        <Loader2 className="w-12 h-12 text-red-600 animate-spin mb-4" />
        <p className="text-xl font-medium text-slate-700">Loading Secure Environment...</p>
      </div>
    }>
      <EmergencyViewContent />
    </Suspense>
  )
}
